version: '3'

services:
  common-codelist-consumer:
   image: fint/common-codelist:1.1.0
   ports:
     - "8000:8000"
   environment:
    TZ: Europe/Oslo
   deploy:
    placement:
     constraints:
      - node.role == worker
    replicas: 3
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s
   networks:
    - fint_common_codelist
networks:
  fint_common_codelist:
    driver: overlay
    external: false